apiVersion: v1
kind: Service
metadata:
  name: musinsa-sre-backend
spec:
  type: NodePort
  selector:
    app: musinsa-sre-backend
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
    nodePort: 30080 # Minikube에서 접근할 포트 (30000~32767 사이)
